import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import { Html, OrbitControls, Stars } from "@react-three/drei";
import FloatText3D from "@/components/FloatText3D";
import { v4 as uuid } from "uuid";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>ideal idea</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen">
        <Canvas>
          <Stars radius={100} count={500} fade={true} />
          <OrbitControls maxDistance={10} />
          <hemisphereLight groundColor="#ff4e8c" color="#34319c" />
          <ambientLight color="#ff4e8c" intensity={0.1} />
          <FloatText3D position={[-4, 0, 0]}>i</FloatText3D>
          <FloatText3D position={[-3.5, 0, 0]}>d</FloatText3D>
          <FloatText3D position={[-2.5, 0, 0]}>e</FloatText3D>
          <FloatText3D position={[-1.5, 0, 0]}>a</FloatText3D>
          <FloatText3D position={[-0.5, 0, 0]}>l</FloatText3D>
          <FloatText3D position={[1, 0, 0]}>i</FloatText3D>
          <FloatText3D position={[1.5, 0, 0]}>d</FloatText3D>
          <FloatText3D position={[2.5, 0, 0]}>e</FloatText3D>
          <FloatText3D position={[3.5, 0, 0]}>a</FloatText3D>
          <Html position={[0, -1, 0]} transform>
            <Link
              href={{
                pathname: "/room",
                query: { c: uuid() },
              }}
              as="/room"
            >
              시작하기
            </Link>
          </Html>
        </Canvas>
      </main>
    </>
  );
}
